#!/bin/bash

addgroup --gid ${GID} lufi \
&& adduser --shell /bin/sh --disabled-password --no-create-home  --ingroup lufi --uid ${UID} --gecos "User" lufi

cd /usr/lufi
mkdir -p data files /themes
chown -R lufi:lufi . /themes

# Outputting directly to lufi.conf using "sed -i" when mounted with docker fails.
echo "$(sed \
        -e 's|<secret>|'${SECRET}'|' \
        -e 's|<contact>|'${CONTACT}'|' \
        -e 's|<report>|'${REPORT}'|' \
        -e 's|<max_file_size>|'${MAX_FILE_SIZE}'|' \
        -e 's|<webroot>|'${WEBROOT}'|' \
        -e 's|<default_delay>|'${DEFAULT_DELAY}'|' \
        -e 's|<max_delay>|'${MAX_DELAY}'|' \
        -e 's|<theme>|'${THEME}'|' \
        -e 's|<allow_pwd_on_files>|'${ALLOW_PWD_ON_FILES}'|' \
        -e 's|<policy_when_full>|'${POLICY_WHEN_FULL}'|' lufi.conf
)" > lufi.conf

if [ -e /themes ]; then
    for theme in $(ls /themes); do
        ln -s /themes/$theme themes/$theme
    done
fi

su lufi -c "/usr/local/bin/carton exec hypnotoad -f /usr/lufi/script/lufi"
